package dz.algerium.browser;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;import java.net.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity{
 EditText address; PageView page; TextView title; ArrayList<String> history=new ArrayList<>(),bookmarks=new ArrayList<>(); String current="about:home";
 @Override public void onCreate(Bundle b){super.onCreate(b); build(); home();}
 Button b(String s){Button x=new Button(this);x.setText(s);x.setTextSize(18);x.setMinWidth(0);x.setPadding(0,0,0,0);return x;}
 LinearLayout.LayoutParams p(int w,int h){return new LinearLayout.LayoutParams(w,h);}
 void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.WHITE);
  LinearLayout tabs=new LinearLayout(this);tabs.setGravity(Gravity.CENTER_VERTICAL);title=new TextView(this);title.setText("  Algerium");title.setTextSize(15);title.setTypeface(null,1);tabs.addView(title,new LinearLayout.LayoutParams(0,44,1));Button plus=b("+");tabs.addView(plus,p(48,44));root.addView(tabs);
  LinearLayout bar=new LinearLayout(this);bar.setPadding(6,4,6,4);Button back=b("‹"),fwd=b("›"),reload=b("↻"),menu=b("⋮");address=new EditText(this);address.setSingleLine();address.setHint("Search or enter address");address.setImeOptions(EditorInfo.IME_ACTION_GO);bar.addView(back,p(40,48));bar.addView(fwd,p(40,48));bar.addView(reload,p(40,48));bar.addView(address,new LinearLayout.LayoutParams(0,48,1));bar.addView(menu,p(40,48));root.addView(bar);
  page=new PageView(this);root.addView(page,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
  address.setOnEditorActionListener((v,a,e)->{navigate(address.getText().toString());return true;});reload.setOnClickListener(v->navigate(current));back.setOnClickListener(v->{if(page.canBack()){current=page.backUrl();navigate(current,false);}});fwd.setOnClickListener(v->{if(page.canForward()){current=page.forwardUrl();navigate(current,false);}});plus.setOnClickListener(v->home());menu.setOnClickListener(v->popup(menu));}
 void popup(View anchor){PopupMenu m=new PopupMenu(this,anchor);m.getMenu().add("New tab");m.getMenu().add("Bookmarks");m.getMenu().add("History");m.getMenu().add("Find in page");m.getMenu().add("Share page");m.getMenu().add("Settings");m.setOnMenuItemClickListener(i->{String s=i.getTitle().toString();if(s.equals("New tab"))home();else if(s.equals("Bookmarks"))showList("Bookmarks",bookmarks);else if(s.equals("History"))showList("History",history);else if(s.equals("Find in page"))find();else if(s.equals("Share page")){Intent x=new Intent(Intent.ACTION_SEND);x.setType("text/plain");x.putExtra(Intent.EXTRA_TEXT,current);startActivity(Intent.createChooser(x,"Share page"));}else if(s.equals("Settings"))settings();return true;});m.show();}
 void find(){final EditText e=new EditText(this);e.setHint("Find text");new AlertDialog.Builder(this).setTitle("Find in page").setView(e).setPositiveButton("Find",(d,w)->page.find(e.getText().toString())).setNegativeButton("Cancel",null).show();}
 void settings(){new AlertDialog.Builder(this).setTitle("Algerium settings").setItems(new String[]{"Search engine: Google","JavaScript: experimental","Block third-party trackers: on","Clear browsing data"},(d,w)->{if(w==3){history.clear();Toast.makeText(this,"Browsing data cleared",Toast.LENGTH_SHORT).show();}}).show();}
 void showList(String t,ArrayList<String> a){new AlertDialog.Builder(this).setTitle(t).setItems(a.toArray(new String[0]),(d,w)->navigate(a.get(w))).setPositiveButton("Close",null).show();}
 void home(){current="about:home";address.setText("");page.home();title.setText("  Algerium");}
 void navigate(String raw){navigate(raw,true);} void navigate(String raw,boolean add){String u=normalize(raw);current=u;address.setText(u);title.setText("  "+u);if(add&&!u.equals("about:home"))history.add(0,u);page.load(u);}
 String normalize(String s){s=s.trim();if(s.isEmpty())return "about:home";if(s.equalsIgnoreCase("algerium://home"))return "about:home";if(!s.matches("(?i)^[a-z][a-z0-9+.-]*://.*")){if(s.contains(" "))return "https://www.google.com/search?q="+URLEncoder(s);return "https://"+s;}return s;}
 String URLEncoder(String s){try{return java.net.URLEncoder.encode(s,"UTF-8");}catch(Exception e){return s;}}
}