package dz.algerium.browser;

import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import java.util.*;import java.util.regex.*;

public class PageView extends View{
 Paint p=new Paint(3);String url="",html="";ArrayList<String> history=new ArrayList<>();int pos=-1;float sy;boolean drag;ArrayList<Block> blocks=new ArrayList<>();
 static class Block{String text;float x,y,w,h;int size;boolean bold,link;Block(String t,float X,float Y,float W,int S,boolean B,boolean L){text=t;x=X;y=Y;w=W;size=S;bold=B;link=L;h=S*1.45f;}}
 public PageView(Context c){super(c);p.setTypeface(Typeface.create("sans",0));setBackgroundColor(Color.WHITE);setFocusable(true);}
 void showDocument(String u,String h){url=u;html=h; if(pos<history.size()-1)history.subList(pos+1,history.size()).clear();history.add(u);pos=history.size()-1;parse();invalidate();}
 void parse(){blocks.clear();String s=html.replaceAll("(?is)<script.*?</script>|<style.*?</style>|<svg.*?</svg>|<!--.*?-->","");s=s.replaceAll("(?is)<br\\s*/?>","\\n");s=s.replaceAll("(?is)</(p|div|section|article|h[1-6]|li|tr|header|footer|main|nav|title)>","\\n\\n");s=s.replaceAll("(?is)<li[^>]*>","• ");s=s.replaceAll("(?is)<[^>]+>","");s=s.replace("&nbsp;"," ").replace("&amp;","&").replace("&lt;","<").replace("&gt;",">").replace("&quot;","\"");
s=s.replaceAll("[ \\t]+"," ").replaceAll("\\n{3,}","\\n\\n").trim();float y=28;for(String para:s.split("\\n+")){String t=para.trim();if(t.isEmpty())continue;int size=(t.length()<70?22:17);boolean bold=t.length()<55;float w=getWidth()>0?getWidth()-32:900;while(t.length()>0){int n=Math.min(t.length(),Math.max(12,(int)(w/(size*.55f))));int cut=n;if(n<t.length()){int k=t.lastIndexOf(' ',n);if(k>5)cut=k;}String part=t.substring(0,cut).trim();t=t.substring(cut).trim();blocks.add(new Block(part,16,y,w,size,bold,false));y+=size*1.55f;}}
 if(blocks.isEmpty())blocks.add(new Block("No readable content was found on this page.",16,30,getWidth()-32,18,false,false));}
 @Override protected void onDraw(Canvas c){super.onDraw(c);c.save();c.translate(0,-scroll);p.setColor(Color.rgb(25,25,28));for(Block b:blocks){p.setTextSize(b.size);p.setTypeface(Typeface.create("sans",b.bold?Typeface.BOLD:Typeface.NORMAL));for(String line:wrap(b.text,b.w,p)){c.drawText(line,b.x,b.y,p);b.y+=b.size*1.5f;}}c.restore();}
 float scroll=0,max=0;ArrayList<String> wrap(String s,float w,Paint paint){ArrayList<String>a=new ArrayList<>();String[] ws=s.split(" ");String line="";for(String q:ws){String z=line.isEmpty()?q:line+" "+q;if(paint.measureText(z)>w&&!line.isEmpty()){a.add(line);line=q;}else line=z;}if(!line.isEmpty())a.add(line);max=Math.max(max,blocks.size()*35);return a;}
 @Override public boolean onTouchEvent(android.view.MotionEvent e){if(e.getAction()==0){sy=e.getY();drag=false;return true;}if(e.getAction()==2){float d=sy-e.getY();if(Math.abs(d)>2)drag=true;scroll=Math.max(0,Math.min(max+getHeight(),scroll+d));sy=e.getY();invalidate();return true;}return true;}
 boolean canBack(){return pos>0;}boolean canForward(){return pos>=0&&pos<history.size()-1;}void back(){pos--;url=history.get(pos);loadHistory();}void forward(){pos++;url=history.get(pos);loadHistory();}void loadHistory(){new Thread(()->{try{java.net.HttpURLConnection c=(java.net.HttpURLConnection)new java.net.URL(url).openConnection();c.setConnectTimeout(10000);String h=new java.io.BufferedReader(new java.io.InputStreamReader(c.getInputStream(),"UTF-8")).lines().reduce("",(a,b)->a+b+"\\n");post(()->{html=h;parse();invalidate();});}catch(Exception ignored){}}).start();}
 void showError(String u,String e){html="";blocks.clear();blocks.add(new Block("Algerium couldn't load this page",20,50,getWidth()-40,24,true,false));blocks.add(new Block(u,20,100,getWidth()-40,16,false,false));blocks.add(new Block(e==null?"Network error":e,20,150,getWidth()-40,16,false,false));scroll=0;invalidate();}
}
