cmake_minimum_required(VERSION 3.20)
project(AlgeriumDesktop LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_subdirectory(../engine ${CMAKE_BINARY_DIR}/engine)
find_package(PkgConfig QUIET)
find_package(SDL2 CONFIG QUIET)
find_package(SDL2_ttf CONFIG QUIET)
find_package(CURL CONFIG QUIET)
if(NOT TARGET SDL2::SDL2 AND PkgConfig_FOUND)
  pkg_check_modules(SDL2 REQUIRED IMPORTED_TARGET sdl2)
  add_library(SDL2::SDL2 ALIAS PkgConfig::SDL2)
  pkg_check_modules(SDL2TTF REQUIRED IMPORTED_TARGET SDL2_ttf)
  add_library(SDL2_ttf::SDL2_ttf ALIAS PkgConfig::SDL2TTF)
endif()
if(NOT TARGET CURL::libcurl AND PkgConfig_FOUND)
  pkg_check_modules(CURLPC REQUIRED IMPORTED_TARGET libcurl)
  add_library(CURL::libcurl ALIAS PkgConfig::CURLPC)
endif()
add_executable(algerium_desktop src/main.cpp)
target_link_libraries(algerium_desktop PRIVATE algerium_engine SDL2::SDL2 SDL2_ttf::SDL2_ttf CURL::libcurl)
if(WIN32)
  if(TARGET SDL2::SDL2main)
    target_link_libraries(algerium_desktop PRIVATE SDL2::SDL2main)
  endif()
  set_target_properties(algerium_desktop PROPERTIES WIN32_EXECUTABLE TRUE)
endif()
